- pkg/knuu/instance.go
> fix: fix buildcontext, it was deleted after func returns

- pkg/k8s/k8s.go
- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
> feat: remove todos in favor of github issies

- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/instance_pool.go
- pkg/knuu/instance_state.go
> feat: split out functions for better overview

- pkg/container/buildah.go
- pkg/k8s/k8s.go
- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_pvc.go
- pkg/k8s/k8s_service.go
- pkg/knuu/initialize.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Closes https://github.com/celestiaorg/knuu/issues/10
> feat: refactor using gpt-3

- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
> feat: Instance prep and reuse

- pkg/knuu/instance.go
Resolves https://github.com/celestiaorg/knuu/issues/48
> fix: setCommand same syntax as setArgs

- pkg/container/docker.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Closes https://github.com/celestiaorg/knuu/issues/7
Blocked by https://github.com/celestiaorg/knuu/pull/35
> feat: dont build push if no changes

- pkg/knuu/instance.go
Adding a few comments for the clone function.
This closes #71
> Adding documentation to Clone function

- pkg/container/docker.go
- pkg/knuu/instance.go
> feat: add SetUser for instance:

- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/instance_state.go
Resolves https://github.com/celestiaorg/knuu/issues/55, resolves https://github.com/celestiaorg/knuu/issues/70
> feat: add Stop functionality

- pkg/knuu/knuu.go
Resolves https://github.com/celestiaorg/knuu/issues/59
> feat: don't deprecate `Initialize()`

- pkg/container/docker.go
- pkg/knuu/instance.go
For clarity added a `AddFolder()` function.
Ref.: https://github.com/celestiaorg/knuu/issues/55
> feat: add folder function

- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Resolves https://github.com/celestiaorg/knuu/issues/45
> remove duplication

- README.md
Resolves https://github.com/celestiaorg/knuu/issues/75, resolves https://github.com/celestiaorg/knuu/issues/81, resolves https://github.com/celestiaorg/knuu/issues/12
> feat: add a proper readme

- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
> fix: volume when running non root user

- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_statefulset.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Resolves https://github.com/celestiaorg/knuu/issues/82
> feat: introduce statefulset

- CONTRIBUTING.md
- README.md
> doc: add contributing.md

- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
> bugfix: proper error handling and retries

- README.md
Using Initialize instead of InitializeWithIdentifier will help new users and won't complicate the examples by using time and identifier variable as they are already defined in Initialize. Resolved linting errors.
Resolves https://github.com/celestiaorg/knuu/issues/139
> Fix: changed InitializedWithIdentifier to Initialize

- README.md
> feat: bump knuu version v0.8 in README

- pkg/k8s/k8s.go
- pkg/k8s/k8s_daemonset.go
- pkg/k8s/k8s_networkpolicy.go
- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_pvc.go
- pkg/k8s/k8s_role.go
- pkg/k8s/k8s_rolebinding.go
- pkg/k8s/k8s_service.go
- pkg/k8s/k8s_serviceaccount.go
- pkg/k8s/k8s_statefulset.go
- pkg/k8s/utils.go
Resolves https://github.com/celestiaorg/knuu/issues/115
> feat: package timeout for k8s communication

- README.md
- pkg/k8s/k8s.go
- pkg/k8s/k8s_daemonset.go
- pkg/k8s/k8s_networkpolicy.go
- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_pvc.go
- pkg/k8s/k8s_role.go
- pkg/k8s/k8s_rolebinding.go
- pkg/k8s/k8s_service.go
- pkg/k8s/k8s_serviceaccount.go
- pkg/k8s/k8s_statefulset.go
- pkg/k8s/utils.go
> feat: Update alpha branch with main branch

- pkg/k8s/k8s_ingress.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/instance_ingress.go
- pkg/knuu/knuu.go
Resolves https://github.com/celestiaorg/knuu/issues/121
Tested here: https://github.com/celestiaorg/knuu-example/blob/ff383fe0820f138f0ce4f7946d0835256087bfca/basic/ingress_test.go
> feat: add capability of creating ingresses

- pkg/k8s/k8s_service.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Resolves https://github.com/celestiaorg/knuu/issues/120
Tested here: https://github.com/celestiaorg/knuu-example/blob/8439f2ba8104b84464a48ca57fa6c734e05fc6b8/basic/external-dns_test.go
> feat: add capability of external dns services

- pkg/k8s/k8s_configmap.go
- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
Tested in branch: https://github.com/celestiaorg/knuu-example/tree/feature/add-file-after-commit
Resolves https://github.com/celestiaorg/knuu/issues/32
> feat: create and attach configMap when adding file after commit

- README.md
- go.mod
- go.sum
- pkg/k8s/k8s.go
- pkg/k8s/k8s_configmap.go
- pkg/k8s/k8s_daemonset.go
- pkg/k8s/k8s_networkpolicy.go
- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_pvc.go
- pkg/k8s/k8s_role.go
- pkg/k8s/k8s_rolebinding.go
- pkg/k8s/k8s_service.go
- pkg/k8s/k8s_serviceaccount.go
- pkg/k8s/k8s_statefulset.go
- pkg/k8s/utils.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/knuu.go
- pkg/knuu/preloader.go
> feat: Update alpha with main branch

- pkg/knuu/knuu.go
Resolves https://github.com/celestiaorg/knuu/issues/164
> bugfix: add configmaps to timeout handler

- README.md
> doc: update feature list in readme

- pkg/knuu/instance_pool.go
> feat: start without wait for instance pool

- pkg/k8s/k8s_pod.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
> feat: use fsGroup

- pkg/knuu/instance_otel.go
> bugfix: use numbers instead of name for owner

- pkg/k8s/k8s_pod.go
> bugfix: set fsGroupChangePolicy to on root mismatch

- pkg/knuu/instance_helper.go
Closes https://github.com/celestiaorg/knuu/issues/212
> feat: only call detroy service when service was deployed

- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/instance_otel.go
> feat: add prometheus exporter and promremotewrite exporter

- pkg/knuu/knuu.go
- pkg/knuu/minio.go
> feat: add minio to test runs

- pkg/container/docker.go
- pkg/container/errors.go
- pkg/k8s/errors.go
- pkg/k8s/k8s.go
- pkg/k8s/k8s_configmap.go
- pkg/k8s/k8s_daemonset.go
- pkg/k8s/k8s_namespace.go
- pkg/k8s/k8s_networkpolicy.go
- pkg/k8s/k8s_pod.go
- pkg/k8s/k8s_pvc.go
- pkg/k8s/k8s_replicaset.go
- pkg/k8s/k8s_role.go
- pkg/k8s/k8s_rolebinding.go
- pkg/k8s/k8s_service.go
- pkg/k8s/k8s_serviceaccount.go
- pkg/knuu/bittwister.go
- pkg/knuu/errors.go
- pkg/knuu/executor.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
- pkg/knuu/instance_otel.go
- pkg/knuu/instance_pool.go
- pkg/knuu/knuu.go
- pkg/knuu/minio.go
- pkg/knuu/preloader.go
- pkg/minio/errors.go
- pkg/minio/minio.go
> chore: refactor all errors to be wrapped

- e2e/celestia_app/networking_test.go
> fix: network condition tests

- pkg/k8s/k8s_pod.go
> fix: port forward function channels

- README.md
- e2e/celestia_app/networking_test.go
- e2e/celestia_app/pool_sync_test.go
- e2e/celestia_app/stop_test.go
- e2e/celestia_app/upgrade_preloaded_test.go
- e2e/celestia_app/upgrade_test.go
- e2e/celestia_node/basic_test.go
- e2e/celestia_node/otel_test.go
- e2e/celestia_node/utils/utils.go
- go.mod
- go.sum
> bugfix: remove usage of knuu-example repo

- e2e/basic/files_to_volumes_cm_test.go
Some of the tests were failing on volume tests, so this PR is a suggestion to fix them.
> fix: file to volumes test

- pkg/builder/builder.go
- pkg/k8s/k8s_service.go
- pkg/knuu/errors.go
- pkg/knuu/instance.go
- pkg/knuu/instance_helper.go
> bugfix: sidecar should use parents service

- pkg/k8s/k8s_replicaset.go
> bugfix: replace statefulset

- .github/auto_request_review.yml
- .github/workflows/housekeeping.yml
- .github/workflows/stale.yml
Add auto reviewer
Add auto labelling for knuu project board
Add auto add to project
This supports the 2 new project board views for managing Knuu
knuu and knuu triage.
> feat(ci): add ci automation

- .github/workflows/knuu_testing.yml
> bugfix: use scope feature in CI

- e2e/basic/bittwister_test.go
> chore: remove 100% packetloss test

- .github/workflows/knuu_testing.yml
> chore: update kube config secret

- pkg/instance/tshark.go
> feat: tshark only few bytes

- .github/workflows/housekeeping.yml
Adding only issues to the new devops project board
> chore(ci): update project board automation
